const message = {
  en: {
    professions: {
      already_exists: 'Profession already exists',
    },
    common: {
      create_success: 'Created successfully',
      update_success: 'Update successfully.',
      list_success: 'List fetched successfully',
      exists: 'Selected detail is already exists,please try with other.',
      not_exists: 'Selected detail is not exists,please try with other.',
      detail_success: 'Detail fetch successfully.',
      user_service_unable: 'Unable to user services.',
    },
    auth: {
      empty_token: "Please provide access token",
      un_authenticate: "Unauthorized user",
      not_access: 'You are not allowed to access this page.',
      blacklist: 'Token is blacklisted',
      not_auth: 'Authenticated user not found',
      token_expired: 'Token is expired.',
    },
    instituteCourse: {
      batch_exists: 'Batch already exists,please try with other.',
      subcourse_invalid: 'Subcourse is invalid,please try with other.',
      course_not_exist: 'Course not exists,please try with other.',
      batch_not_exist: 'Batch not exists,please try with other.',
      start_end_time_invalid: 'Start time must be before end time',
    },
    instituteLead: {
      not_exists: 'Institute Lead not exists,please try with other.',
      stage_not_exists: 'Stage not exists,please try with other.',
      course_invalid: 'Course Id is invalid,please try with other.',
      subCourse_invalid: 'SubCourse Id is invalid,please try with other.',
      batch_invalid: 'Batch Id is invalid,please try with other.',
      not_access: 'You are not allowed to access this page.',
      sub_stage_not_exists: 'Sub Stage not exists,please try with other.',
      child_stage_not_exists: 'Child Stage not exists,please try with other.',
      batch_not_exist: 'Batch not exists,please try with other.',
      stage_not_exist: 'Stage not exists,please try with other.',
      user_id_not_exists: 'Selected user does not exists.',
      lead_not_exists: 'Selected lead does not exists.',
      number_not_exists: 'Selected phone number does not exists.',
      ivrs_number_invalid: 'IVRS campaign number is invalid.',
      agent_user_invalid: 'Selected agaent user does not exists.',
      customer_number_invalid: 'Customer number is invalid.',
      delete_success: 'Lead deleted successfully.',
      source_key_invalid: 'Source key invalid.',
      source_key_invalid_other: 'Source key invalid,please try with other.',
      tata_call_limit_exceeded: "Please wait at least 1 minutes before making another call.",
      tata_call_success: "Tata call initiated successfully..",
      import_success: "Institute Leads Imported Successfully"
    },
    project: {
        not_exists: 'Selected project is not exists,please try with another.',
        file_already_exists: 'Project file already created.',
        bank_exists: 'Bank detail is already created.',
        doc_exists: 'Project document is already created.',
        seo_exists: 'Project SEO detail is already exists.',
        account_exists: 'Account detail is already exists.',
        partner_not_exists: 'Selected project partner id is not exists.',
        file_not_exists: 'Project file details does not exists.',
        construction_not_exists: 'Construction id does not exists.',
        bank_not_exists: 'Bank detail id does not exists.',
        account_not_exists: 'Account detail id does not exists.',
        doc_not_exists: 'Document id does not exists.',
        seo_not_exists: 'SEO id does not exists.',
        exists: 'Projects already exists,please try with other.',
        stage_not_exists: 'Project stage does not exists.',
        sub_stage_not_exists: 'Project sub stage does not exists.',
        child_stage_not_exists: 'Project child stage does not exists.',
        not_access: 'You are not allowed to access this page.',
        user_id_not_exists: 'Selected user does not exists.',
        lead_not_exists: 'Selected lead does not exists.',
        block_not_exists: 'Selected Block id is not exists.',
        floor_not_exists: 'Selected Floor id is not exists.',
        amenities_not_exists: 'Selected Amenities id is not exists.',
        gallery_not_exists: 'Selected Gallery id is not exists.',
        advance_exists: 'Advance detail is already exists.',
        advance_id_not_exists: 'Selected advance detail id does not exists.',
        number_not_exists: 'Selected phone number does not exists.',
        ivrs_number_invalid: 'IVRS campaign number is invalid.',
        agent_user_invalid: 'Selected agaent user does not exists.',
        customer_number_invalid: 'Customer number is invalid.',
        tata_call_limit_exceeded: "Please wait at least 1 minutes before making another call.",
        tata_call_success: "Tata call initiated successfully..",
        tata_call_failed: "Tata call failed. Please try again later.",
        whatsapp_message_success: 'Whatsapp message sent successfully.',
        delete_success: 'Deleted successfully.',
        user_type_not_exists: 'User type does not exists.',
        referral_not_exists: 'Referral does not exists.',
        lead_exist: 'Lead already exists.',
        referral_invalid: 'Referral id provided is invalid.',
        unit_not_exists: 'Unit does not exists.',
        plan_not_exists: 'Payment plan does not exists.',
        plan_detail_not_exists: 'No active payment plan found for this project',
        plan_not_start_End: 'This payment plan is ended or not yet started',
        source_key_invalid: 'Source key invalid.',
        source_key_invalid_other: 'Source key invalid,please try with other.',
    }
  },

  hi: {
    auth: {
      empty_token: 'कृपया एक्सेस टोकन प्रदान करें',
      un_authenticate: 'अनधिकृत उपयोगकर्ता',
    },
  },
};

module.exports = message;
